  # Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/AliyunContainerService/image-syncer
    steps:
    - checkout
    - run:
        name: run tests
        command: |
          test -z $(go fmt ./...)
          go vet ./...
          go test -race -v ./...
    - run:
        name: codecov
        command: |
          go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)
    - run:
        name: compile
        command: |
          make -B
  code-check:
    docker:
      - image: sunyuan3/gometalinter:v1
    working_directory: /go/src/github.com/AliyunContainerService/image-syncer
    steps:
      - checkout
      - run:
          name: validate go code with gometalinter
          command: |
            gometalinter --disable-all --skip vendor -E goconst -E gofmt -E ineffassign -E goimports -E golint -E misspell -E vet -d ./...
      - run:
          name: use opensource tool client9/misspell to correct commonly misspelled English words 
          command: |
            find  ./* -name  "*"  | grep -v vendor | xargs misspell -error
      - run:
          name: detect deadcode without tests folder
          command: |
            gometalinter --disable-all --skip vendor --skip tests -E deadcode -d ./...
      - run:
          name: use markdownlint v0.5.0 to lint markdown file (https://github.com/markdownlint/markdownlint)
          command: |
            find  ./ -name  "*.md" | grep -v vendor | grep -v commandline |  grep -v .github |  grep -v swagger |  grep -v api |  xargs mdl -r ~MD009,~MD010,~MD013,~MD024,~MD029,~MD033,~MD036
  markdown-spellcheck:
    docker:
        - image: sunyuan3/markdown-spellcheck:v1
    working_directory: /go/src/github.com/AliyunContainerService/image-syncer
    steps:
      - checkout
      - run:
          name: markdown spellcheck
          command: |
            find . -name \*.md | grep -v '^./vendor' | grep  -v ./README-zh_C | xargs mdspell --ignore-numbers --ignore-acronyms --en-us -r -x
workflows:
  version: 2
  ci:
    jobs:
      - build
      - code-check
      - markdown-spellcheck